name: media_picker
description: An audio/video/image picker in pure Dart, support multi picking.
version: 1.1.0
repository: https://github.com/TuanMinhVan/media_picker
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.1.1
  provider: ^6.1.2
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
