// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKsgArlO5v3L-KAstNuiPnQf883kkF50',
    appId: '1:292783235989:web:bea2d9113c8a095f65cc9c',
    messagingSenderId: '292783235989',
    projectId: 'demoapp-7f370',
    authDomain: 'demoapp-7f370.firebaseapp.com',
    storageBucket: 'demoapp-7f370.appspot.com',
    measurementId: 'G-PJR3RCV1C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMj-0C_KLICFccxOW1M1xlTnASEYQbj1A',
    appId: '1:292783235989:android:96446590e3103d4365cc9c',
    messagingSenderId: '292783235989',
    projectId: 'demoapp-7f370',
    storageBucket: 'demoapp-7f370.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfh6mfo6ZF1ADpuS2ULaw6eeBJ_0ufBDU',
    appId: '1:292783235989:ios:233372df0f3e76dd65cc9c',
    messagingSenderId: '292783235989',
    projectId: 'demoapp-7f370',
    storageBucket: 'demoapp-7f370.appspot.com',
    androidClientId: '292783235989-c1v8h770itgor6f94spojc272sl55ov0.apps.googleusercontent.com',
    iosClientId: '292783235989-6g40f15kg4gaem82bi1tv1g3ccvstqcd.apps.googleusercontent.com',
    iosBundleId: 'gmo.codebase.com',
  );
}
